#if !defined(AFX_PFCONVRT_H__ADAE6B3E_3E12_4CF5_B7BE_EB2C9DF755C9__INCLUDED_)
#define AFX_PFCONVRT_H__ADAE6B3E_3E12_4CF5_B7BE_EB2C9DF755C9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPFConvrt wrapper class

class CPFConvrt : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPFConvrt)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7bdb9ce3, 0x6856, 0x11cf, { 0x8f, 0x5f, 0x0, 0x60, 0x8c, 0xea, 0x42, 0x82 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetSource();
	void SetSource(LPCTSTR);
	CString GetDestination();
	void SetDestination(LPCTSTR);
	long GetSourceType();
	void SetSourceType(long);
	long GetDestinationType();
	void SetDestinationType(long);
	BOOL GetWriteDefaults();
	void SetWriteDefaults(BOOL);
	BOOL GetExternalGraphicsFile();
	void SetExternalGraphicsFile(BOOL);
	BOOL GetPleaseWait();
	void SetPleaseWait(BOOL);
	BOOL GetSkipPrefix();
	void SetSkipPrefix(BOOL);
	long GetWPGFlags();
	void SetWPGFlags(long);
	long GetDestinationTypeEnum();
	void SetDestinationTypeEnum(long);
	long GetSourceTypeEnum();
	void SetSourceTypeEnum(long);

// Operations
public:
	long Execute();
	short DetectFileFormat();
	void SetFlags();
	long OCXToPF(long OCXType);
	long PFToOCX(long PFType);
	CString ErrorString(long ErrNum);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PFCONVRT_H__ADAE6B3E_3E12_4CF5_B7BE_EB2C9DF755C9__INCLUDED_)
