//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TBTUTTST.RC
//
#define IDD_DIALOG1                     101
#define ID_TEST                         101
#define IDI_ICON1                       102
#define ID_EXIT                         102
#define IDR_MENU1                       103
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT6                       1002
#define IDC_EDIT5                       1003
#define IDC_EDIT4                       1004
#define IDC_EDIT3                       1005
#define IDC_EDIT7                       1006
#define IDC_EDIT8                       1007
#define IDC_EDIT9                       1008
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         103
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
