
// Menu ids

// Main Menu

//file menu
#define IDM_FNEWFLST     101
#define IDM_FNEWCPG      102
#define IDM_FNEWCFL      103

#define IDM_FOPENBDAT    105
#define IDM_FOPENFLST    106
#define IDM_FOPENCPG     107
#define IDM_FOPENCFL     108

#define IDM_FSAVE        109
#define IDM_FSAVEFLST    110
#define IDM_FSAVECFL     111

#define IDM_FSAVEAS      112
#define IDM_FSAVEASFLST  113
#define IDM_FCLOSE       124

#define IDM_FEXPORT      114
#define IDM_FVIEW        115
#define IDM_FEDIT        116
#define IDM_FKILL        117
#define IDM_FPRINT       118
#define IDM_FGRPAGESETUP 119
#define IDM_FPRPAGESETUP 120
#define IDM_FPSETUPGRA   121
#define IDM_FPSETUPTXT   122
#define IDM_FEXIT        123
#define IDM_F1           125
#define IDM_F2           126
#define IDM_F3           127
#define IDM_F4           128
#define IDM_F5           129
#define IDM_F6           130

//edit menu
#define IDM_EUNDO        201
#define IDM_EREDO        202
#define IDM_ECUT         203
#define IDM_ECOPY        204
#define IDM_EPASTE       205
#define IDM_EDEL         206
#define IDM_EFIND        207
#define IDM_ENEXT        208

//data menu
#define IDM_DBIRTHI      301
#define IDM_DCOMPATI     302
#define IDM_DTRANSI      303
#define IDM_DTRANSD      304
#define IDM_DPROGD       305
#define IDM_DBIRTHR      306
#define IDM_DCOMPATR     307
#define IDM_DRETURND     308
#define IDM_DRELOCD      309

//chart menu
#define IDM_CDEF        401
#define IDM_CBSO        402
#define IDM_CBSH        403
#define IDM_CBSHA       404
#define IDM_CCOMPLETE   405
#define IDM_CCMPBASM    406
#define IDM_CCMPFLM     407
#define IDM_CNUMERIC    408
#define IDM_CCOMPAT     409
#define IDM_CTRANS      410
#define IDM_CPROGR      411
#define IDM_CCOMPOS     412
#define IDM_CCMTR       413
#define IDM_CRELOC      414
#define IDM_CRETURN     415
#define IDM_CFIXED      416
#define IDM_CARABIC     417
#define IDM_CHELIO      418
#define IDM_CPROB       419

//window menu
#define IDM_WARRANGE    501
#define IDM_WCASCADE    502
#define IDM_WTILE       503
#define IDM_W1          504
#define IDM_W2          505
#define IDM_W3          506
#define IDM_W4          507
#define IDM_W5          508
#define IDM_WTEXTLST    530
#define IDM_WGRAPLST    531

//options menu
#define IDM_OSETUP      601
#define IDM_OTEXT       602
#define IDM_OGRAPHICS   603
#define IDM_OGRPHFIL    604
#define IDM_OVIEW       605
#define IDM_OEDIT       606
#define IDM_OEORBS      607
#define IDM_ONATAL      608
#define IDM_OCOMPAT     609
#define IDM_OTRANS      610
#define IDM_OPROGR      611
#define IDM_OCOMPOS     612
#define IDM_OCMTR       613
#define IDM_ORELOC      614
#define IDM_ORETURN     615
#define IDM_OFIXED      616
#define IDM_OARABIC     617
#define IDM_ONUMER      618
#define IDM_OPROB       619
#define IDM_OALLCK      620
#define IDM_OQDT        621

//utilities
#define IDM_UBATCH      701
#define IDM_UMACROS     702
#define IDM_UPARSE      703
#define IDM_UIBIRTH     704
#define IDM_UILOCAT     705
#define IDM_UIALLD      706
#define IDM_UPBIRTH     707
#define IDM_UPLOCAT     708
#define IDM_UPALLD      709
#define IDM_UMBIRTH     710
#define IDM_UMLOCAT     711
#define IDM_UBLDFLST    712
#define IDM_UCLRSEL     713
#define IDM_UEDIT       714
#define IDM_USORT       715
#define IDM_UARC        716
#define IDM_UXARC       717

//help
#define IDM_HCONTENTS   801
#define IDM_HSEARCH     802
#define IDM_HHOWTO      803
#define IDM_HASTROL     804
#define IDM_HABOUT      805
#define IDM_HINDEX      806

// other menus

//File Type
#define IDM_FTBIRTH     901
#define IDM_FTASTHLPER  902
#define IDM_FTTEXT      903
#define IDM_FTGRAPH     904
#define IDM_FTCOVER     905
#define IDM_FTCOMMENT   906

//Graphics
#define IDM_SIGN_NAME           1001
#define IDM_HOUSE_NUM           1002
#define IDM_HOUSE_DEG           1003
#define IDM_SHOW_ASPT           1004
#define IDM_USE_GLYPH           1005
#define IDM_SHOW_SLIN           1006
#define IDM_GUSESFNT            1007
#define IDM_USE_INHC            1008
#define IDM_SIGN_TICK           1009
#define IDM_DEC_TICK            1010
#define IDM_DEG_TICK            1011
#define IDM_HOUS_OUTS           1012
#define IDM_PLOT_CLASSIC        1013
#define IDM_SHOW_DEGS           1014
#define IDM_GNEXTC              1015
#define IDM_GSHPREVC            1016
#define IDM_GSHFIRST            1017
#define IDM_GDECHSE             1018
#define IDM_GINCHSE             1019
#define IDM_GREGHSE             1020
#define IDM_ZOOMIN              1021
#define IDM_ZOOMOUT             1022
#define IDM_FITWIN              1023
#define IDM_SHOW_AGRID          1024

//Birth Database
#define IDM_BDBGET      1101
#define IDM_BDBADD      1102
#define IDM_BDBREPLACE  1103
#define IDM_BDBDEL      1104
#define IDM_BDBMKPOP    1105
#define IDM_BDBCOPY     1106
#define IDM_BDBPASTE    1107
#define IDM_BDBCLEAR    1108
#define IDM_BDBRETURN   1109

//Location Database
#define IDM_LDBGET      1201
#define IDM_LDBADD      1202
#define IDM_LDBREPLACE  1203
#define IDM_LDBDEL      1204
#define IDM_LDBCOPY     1205
#define IDM_LDBPASTE    1206
#define IDM_LDBCLEAR    1207
#define IDM_LDBRETURN   1208




