#ifndef DIALOGS__H__
#define DIALOGS__H__

#define IDC_NO                      200
#define IDC_BDAM                    116
#define IDC_BDBDM                   145
#define IDC_BDCO                    119
#define IDC_BDDAY                   108
#define IDC_BDGH                    140
#define IDC_BDGM                    141
#define IDC_BDHR                    112
#define IDC_BDLAD                   131
#define IDC_BDLAM                   133
#define IDC_BDLANS                  134
#define IDC_BDLO                    123
#define IDC_BDLOD                   125
#define IDC_BDLOEW                  128
#define IDC_BDLOM                   127
#define IDC_BDLOMEN                 146
#define IDC_BDMIN                   114
#define IDC_BDMO                    106
#define IDC_BDNM                    102
#define IDC_BDREC                   147
#define IDC_BDSC                    139
#define IDC_BDST                    121
#define IDC_BDSX                    104
#define IDC_BDTZ                    151
#define IDC_BDYR                    110



#define IDC_CSRELOC                 101
#define IDC_CSPROGR                 102
#define IDC_CSPROGCUSP              103

#define IDC_CSTEXT                  106
#define IDC_CSGRAPH                 107
#define IDC_CSDATAFILE              108
#define IDC_CSDFT                   110
#define IDC_CSGETOPTS               111


#define IDC_HELP                    150


#define IDC_OPTROPIC                102
#define IDC_OPSIDEREAL              103


#define IDC_OPHOUSEPROC             105
#define IDC_OPFHOUSE                106
#define IDC_OPFASPECT               107
#define IDC_OPFXASPECT              108
#define IDC_OPFMISC                 109
#define IDC_OPFXMISC                110
#define IDC_OPSUMMARY               111
#define IDC_OPFVERTEAST             112
#define IDC_OPPRTEXT                113
#define IDC_OPFBMID                 114
#define IDC_OPFFMID                 115
#define IDC_OPFHMID                 116
#define IDC_OPFAMID                 117

#define IDC_OPHOUSET                123

#define IDC_RANGLE                  112
#define IDC_RBTAM                   110
#define IDC_RBTH                    106
#define IDC_RBTKNOWN                101
#define IDC_RBTM                    108
#define IDC_RBTMETH                 103
#define IDC_RDEG                    116
#define IDC_RMIN                    118
#define IDC_RSIGN                   114
#define IDC_TDCNT                   114
#define IDC_TDDAY                   112
#define IDC_TDEP                    107
#define IDC_TDMO                    110
#define IDC_TDSP                    105
#define IDC_PROGR                   102
#define IDC_PYR                     104
#define IDC_PMO                     106
#define IDC_PDAY                    108
#define IDC_FNAME                   102
#define IDC_FCOMMENT                104
#define IDC_FTYPE                   106
#define IDC_FFNAME                  108
#define IDC_FKASK                   109
#define IDC_RBODY                   102
#define IDC_RSMO                    105
#define IDC_RSDAY                   107
#define IDC_RSYR                    109
#define IDC_REMO                    112
#define IDC_REDAY                   114
#define IDC_REYR                    116
#define IDC_RPROG                   118
#define IDC_RPROGSYS                120
#define IDC_RPYR                    123
#define IDC_RPMO                    125
#define IDC_RPDAY                   127
#define IDC_RPTARGET                129

#define IDC_CVLFT                   102
#define IDC_CVWID                   104
#define IDC_CVCMT                   105
#define IDC_CVCPG                   106
#define IDC_CVFMT                   108
#define IDC_CVSTYLES                114
#define IDC_CVPSEUDO                115
#define IDC_CVCB4                   116

#define IDC_DSMAIN                  106
#define IDC_DSHELP                  107
#define IDC_DSDB                    108
#define IDC_DSDATA                  109
#define IDC_DSUSER                  110

#define IDC_PGLT                    103
#define IDC_PGRT                    105
#define IDC_PGHT                    108
#define IDC_PGWD                    110
#define IDC_PGTOP                   112
#define IDC_PGBTM                   114

#define IDC_POCPG                   101
#define IDC_POCMT                   102
#define IDC_POALL                   107
#define IDC_PORANGE                 108
#define IDC_POFROM                  110
#define IDC_POTO                    112
#define IDC_POHDP1                  118
#define IDC_POCMTBF                 119
#define IDC_POCNTR                  120
#define IDC_POSTYLES                121

#define IDC_CPIMAGE                 102
#define IDC_CPFILE                  104
#define IDC_CPTITLE                 106
#define IDC_CPNAME                  108
#define IDC_CPCOMMENTS              110
#define IDC_CPFONT                  112
#define IDC_CPASTR                  114

#define IDC_HFILES                  101
#define IDC_HVIEW                   102
#define IDC_HPRINT                  103
#define IDC_HCONV                   104

    
#define IDC_PRSYS                   102
#define IDC_PRYR                    104
#define IDC_PRMO                    106
#define IDC_PRDAY                   108
#define IDC_PRTARGET                110


#define IDC_OECONTEXT               102
#define IDC_OEDGM1                  110
#define IDC_OEINC1                  111
#define IDC_OEDGM2                  113
#define IDC_OEINC2                  114
#define IDC_OEDGM3                  116
#define IDC_OEINC3                  117
#define IDC_OEDGM4                  119
#define IDC_OEINC4                  120
#define IDC_OEDGM5                  122
#define IDC_OEINC5                  123
#define IDC_OEDGM6                  125
#define IDC_OEINC6                  126
#define IDC_OEDGM7                  128
#define IDC_OEINC7                  129
#define IDC_OEDGM8                  131
#define IDC_OEINC8                  132
#define IDC_OEDGM9                  134
#define IDC_OEINC9                  135
#define IDC_OEDGM10                 137
#define IDC_OEINC10                 138
#define IDC_OEDGM11                 140
#define IDC_OEINC11                 141
#define IDC_OEDGM12                 143
#define IDC_OEINC12                 144
#define IDC_OEDGM13                 146
#define IDC_OEINC13                 147
#define IDC_OEDGMNP                 153
#define IDC_OEDGMHS                 155
#define IDC_OEINCHS                 156


#define IDC_SHOW_SIGNNAME           101
#define IDC_SHOWHCD                 102
#define IDC_SHOWHCN                 103
#define IDC_SHOWSIGL                104
#define IDC_SHOWASPL                105
#define IDC_USEGL                   106
#define IDC_HSNMOUT                 107
#define IDC_PLOTCLASS               108
#define IDC_SHOWDEGS                121
#define IDC_SIGNTICK                110
#define IDC_DECTICK                 111
#define IDC_DEGTICK                 112
#define IDC_FONTSIZE                114
#define IDC_GFONTS                  115
#define IDC_GCOLORS                 117
#define IDC_SHOWAGRID               122

#define IDC_SBOLD                   101
#define IDC_EBOLD                   102
#define IDC_SSCORE                  103
#define IDC_ESCORE                  104
#define IDC_SHEAD                   105
#define IDC_EHEAD                   106


#define IDC_EDNAME                  102
#define IDC_EDOPT                   104


#define IDC_RCREG                   101
#define IDC_RCBOLD                  102
#define IDC_RCHEAD                  103
#define IDC_RCITAL                  104


#define BR 8
#define RISE 6
#define PLAN 7
#define SIGN 2
#define HOUS 4
#define CIRC 8
#define GRAPH_COLOR_FIRST           101
#define IDC_GCBACK                  GRAPH_COLOR_FIRST
#define IDC_GCSIGN                  GRAPH_COLOR_FIRST + SIGN
#define IDC_GCHOUSE                 GRAPH_COLOR_FIRST + HOUS
#define IDC_GCPLAN                  GRAPH_COLOR_FIRST + PLAN
#define IDC_GCASCEND                GRAPH_COLOR_FIRST + RISE + BR
#define IDC_GCBSIGN                 GRAPH_COLOR_FIRST + SIGN + BR
#define IDC_GCBHOUSE                GRAPH_COLOR_FIRST + HOUS + BR
#define IDC_GCBPLAN                 GRAPH_COLOR_FIRST + PLAN + BR
#define IDC_GCCIRC                  GRAPH_COLOR_FIRST + CIRC


#define STRINGBLOCK 999
#define PROG_SYS     101
#define SB_MALE      102
#define SB_AMPM      103
#define SB_WPFMT     104
#define SB_FONT      105
#define SB_IMAGE1    106
#define SB_HOUSE     107
#define SB_DATFILE   108
#define SB_CONTEXT   109
#define SB_SIGNS     110
#define SB_ANGLE     111
#define SB_RECTM     112
#define SB_NORTH     113
#define SB_WEST      114
#define SB_SPECC     115
#define SB_TZONE     116
#define SB_BODY      117
#define SB_PLANET    118
#define SB_GFFORMAT  119
#define SB_SIZEUNIT    120
#define SB_RESOLUTION  121
#define SB_IMAGE2    122
#define SB_LONGTYPE  123

#define IDC_PRPRINTERS   101
#define IDC_PRSETUP      106
#define IDC_PROPTIONS    107

#define IDC_GLYPHFONT    101
#define IDC_DEGFONT      102

#define IDC_PASHEAD                 101
#define IDC_PAEHEAD                 102
#define IDC_PASBOLD                 103
#define IDC_PAEBOLD                 104
#define IDC_SASSCORE                105
#define IDC_SAESCORE                106

#define IDC_TXTEXT                  102

#define IDC_AARC                    102
#define IDC_APROG                   104
#define IDC_ADEL                    105
#define IDC_ALHA                    107
#define IDC_AZIP                    108

#define IDC_GFFORMAT                101
#define IDC_GFSTHT                  103
#define IDC_GFSTWD                  104
#define IDC_GFHEIGHT                105
#define IDC_GFWIDTH                 106
#define IDC_GFUNITS                 108
#define IDC_GFREVERSE               109
#define IDC_GFROTATE                110
#define IDC_GFRESOLUTION            112

#define IDC_PIPNAME                 102
#define IDC_PIPDEG                  104
#define IDC_PIPHOUSE                106
#define IDC_PIPDEC                  108

#define IDC_QDTRO       101
#define IDC_QDTRT       102
#define IDC_QDTFH       105
#define IDC_QDTFM       107
#define IDC_QDTFAM      109
#define IDC_QDTLH       112
#define IDC_QDTLM       114
#define IDC_QDTLAM      116

#include "helpid.h"

#endif /* DIALOGS__H__ */
