#ifndef _TXTDRV___H___
#define _TXTDRV___H___

/* Text word processing converter drivers */
#define PLASCIIDOS  0
#define PLASCIIANS  1
#define PLASCNBDOS  2
#define PLASCNBANS  3
#define ASCIITXDOS  4
#define ASCIITXANS  5
#define ASCIINBANS  6
#define ASCIINBDOS  7
#define WS3         8
#define WS4         9
#define WORDPFC4    10
#define WORDPFC5    11
#define WORDPFC6    12
#define XYWRITE     13
#define XYWRINB     14
#define MS_RTFDOS   15
#define MS_RTFANS   16
#define MS_WRITE    17
#define AMIPRO      18
//#define WORDPFCI    19
#define WWW_HTML    19
#define NTEXTD      21

#endif /* _TXTDRV___H___  */
