//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Astrow.rc
//
#define ID_CANCEL                       2
#define ID_FNSELFILE                    3
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDD_ABOUTBOX                    100
#define ID_CSCOGROUP                    100
#define ID_RSREG                        101
#define ID_PSHEAD                       101
#define ID_GOSIGN_NAME                  101
#define ID_GLYPHFNT                     101
#define ID_GCBACK                       101
#define ID_GFFORMAT                     101
#define ID_AHLIST                       101
#define ID_RDCHECK                      101
#define ID_QDONCE                       101
#define ID_POCOVER                      101
#define ID_OPCTGRP                      101
#define ID_CS_RELOC                     101
#define ID_RSBOLD                       102
#define ID_PEHEAD                       102
#define ID_COLEFT                       102
#define ID_GOHOUSE_DEG                  102
#define ID_DATAFNT                      102
#define ID_FNNAME                       102
#define ID_FKNAME                       102
#define ID_FENAME                       102
#define ID_AHVIEW                       102
#define ID_BINAME                       102
#define ID_RDBODY                       102
#define ID_QDRESTRICTTIM                102
#define ID_PDSYSTEM                     102
#define ID_POCMT                        102
#define ID_AOCONTEXT                    102
#define ID_OPTROPICAL                   102
#define ID_CSPROGR                      102
#define ID_CPIMAGE                      102
#define ID_ARNAME                       102
#define IDC_PATH                        102
#define ID_RSHEAD                       103
#define ID_PSBOLD                       103
#define ID_GOHOUSE_NUM                  103
#define ID_GCSIGN                       103
#define ID_GFHTU                        103
#define ID_AHPRINT                      103
#define ID_RDMETHOD                     103
#define ID_OPSIDEREAL                   103
#define ID_CSPRGCUSP                    103
#define ID_RSSCORE                      104
#define ID_PEBOLD                       104
#define ID_COWIDTH                      104
#define ID_GOSIGLINE                    104
#define ID_GFWDU                        104
#define ID_FNCOMMENT                    104
#define ID_FKCOMMENT                    104
#define ID_FECOMMENTS                   104
#define ID_AHCONVERT                    104
#define ID_PDYEAR                       104
#define ID_CPGRAPHIC                    104
#define ID_BISEX                        104
#define ID_ARCMD                        104
#define ID_OPTIONS                      104
#define ID_PSSCORE                      105
#define ID_COCMT                        105
#define ID_GOSHOW_ASPT                  105
#define ID_GCHOUSE                      105
#define ID_GFHEIGHT                     105
#define ID_TDSTART                      105
#define ID_RDSMO                        105
#define ID_QDFHR                        105
#define ID_OPHOUSEPROC                  105
#define ID_CSOOGROUP                    105
#define ID_PESCORE                      106
#define ID_COCPG                        106
#define ID_GOUSE_GLYPHS                 106
#define ID_GFWIDTH                      106
#define ID_DMAIN                        106
#define ID_FNTYPE                       106
#define ID_FKTYPE                       106
#define ID_FETYPE                       106
#define ID_BIMO                         106
#define ID_RDHRS                        106
#define ID_PDMO                         106
#define ID_OPHOUSES                     106
#define ID_CSTEXT                       106
#define ID_CPTITLE                      106
#define ID_ARGRP                        106
#define ID_GOHSNUM_OUTS                 107
#define ID_DHELP                        107
#define ID_TDEND                        107
#define ID_RDSDAY                       107
#define ID_QDFMIN                       107
#define ID_OPASPECTS                    107
#define ID_CSGRAPH                      107
#define ID_ARLHA                        107
#define ID_COFORMAT                     108
#define ID_GOPLOT_CLASS                 108
#define IDC_GCPLAN                      108
#define ID_GFUNITS                      108
#define ID_DDATABASE                    108
#define ID_FKFILENAME                   108
#define ID_FEFILENAME                   108
#define ID_BIDAY                        108
#define ID_RDMIN                        108
#define ID_PDDAY                        108
#define ID_OPEXTASP                     108
#define ID_CSDATAFILE                   108
#define ID_CP_SUBJECT                   108
#define ID_ARZIP                        108
#define ID_GCCIRC                       109
#define ID_GFREVGRA                     109
#define ID_DDATA                        109
#define ID_FKCONTINUE                   109
#define ID_RDSYEAR                      109
#define ID_QDFAMPM                      109
#define ID_OPMISC                       109
#define ID_GOSIGN_TICK                  110
#define ID_DUSER                        110
#define ID_BIYEAR                       110
#define ID_TDMO                         110
#define ID_RDAMPM                       110
#define ID_PDTARGET                     110
#define ID_AODCONJUNCT                  110
#define ID_OPEXTMISC                    110
#define ID_CSDFTYPE                     110
#define ID_CPCOMMENT                    110
#define ID_GODEC_TICK                   111
#define ID_GCBSIGN                      111
#define ID_AOICONJUNCT                  111
#define ID_OPSUMMARY                    111
#define ID_CSCUSTOM                     111
#define ID_GODEG_TICK                   112
#define ID_GFRES                        112
#define ID_BIHR                         112
#define ID_TDDAY                        112
#define ID_RDEMO                        112
#define ID_RDKNOWNANGL                  112
#define ID_QDLHR                        112
#define ID_OPVERTEAST                   112
#define ID_CPFONT                       112
#define ID_GCBHOUSE                     113
#define ID_AODSEXTILE                   113
#define ID_OPTEXT                       113
#define ID_COSTYLES                     114
#define ID_GOFONTSIZE                   114
#define ID_BIMIN                        114
#define ID_TDNUM                        114
#define ID_RDEDAY                       114
#define ID_RDKSIGN                      114
#define ID_QDLMIN                       114
#define ID_AOISEXT                      114
#define IDOPMBASE                       114
#define ID_CPASTROLOGER                 114
#define ID_COPSEUDO                     115
#define ID_GOFONTS                      115
#define ID_GCASCEND                     115
#define ID_OPMFULL                      115
#define ID_FILE_VIEW                    115
#define ID_COCB4                        116
#define ID_GCBPLAN                      116
#define ID_BIAMPM                       116
#define ID_RDEYEAR                      116
#define ID_RDKDEG                       116
#define ID_QDLAMPM                      116
#define ID_AODTRINE                     116
#define ID_OPMHALF                      116
#define ID_GOCOLORS                     117
#define ID_AOITRINE                     117
#define ID_OPMMIDASP                    117
#define ID_FILE_KILL                    117
#define ID_STATIC                       117
#define ID_RDPROG                       118
#define ID_RDKMIN                       118
#define ID_POHDP1                       118
#define ID_STATIC2                      118
#define ID_RLCOUNTRY                    119
#define ID_CMTB4T                       119
#define ID_AODOPPOSE                    119
#define ID_RDPROGSYS                    120
#define ID_POCTRHD                      120
#define ID_AOIOPPOSE                    120
#define ID_GOSHOW_PDEG                  121
#define ID_RLSTATE                      121
#define ID_POSTYLES                     121
#define ID_GOSHOW_AGRID                 122
#define ID_AODSQUARE                    122
#define ID_RLLOCATION                   123
#define ID_RDPYEAR                      123
#define ID_AOISQUARE                    123
#define ID_RLLODEG                      125
#define ID_RDPMO                        125
#define ID_AODSSEXT                     125
#define ID_AOISSEXT                     126
#define ID_RLLOMIN                      127
#define ID_RDPDAY                       127
#define IDR_MAINFRAME                   128
#define ID_RLEASTWEST                   128
#define ID_AODSSQARE                    128
#define IDR_ASTROWTYPE                  129
#define ID_RDTARGET                     129
#define ID_AOISSQUARE                   129
#define IDR_ASTRFLTYPE                  130
#define IDB_GLYPH                       130
#define IDR_MAINFRAME1                  130
#define IDD_PAGESETP                    131
#define IDB_TEXT                        131
#define ID_RLLADEG                      131
#define ID_AODSSESQUIQ                  131
#define IDS_STRING131                   131
#define IDR_ASTROVTYPE                  132
#define IDB_CHECK                       132
#define ID_AOISSESQUIQ                  132
#define IDR_ASTROGTYPE                  133
#define ID_RLLAMIN                      133
#define ID_RLNORTHSOUTH                 134
#define ID_AODQUIN                      134
#define IDR_ASTROVTYPE1                 134
#define ID_AOIQUINCUNX                  135
#define IDR_ASTROFLTYPE                 135
#define IDR_ASTROGTYPE1                 135
#define IDR_ASTROHTYPE                  136
#define ID_AODBIQUI                     137
#define IDD_OPTIONS                     137
#define ID_AOIBQUINT                    138
#define IDD_MSG                         138
#define ID_RLSPECCODE                   139
#define IDD_PROGRESS_DATA               139
#define IDB_TITLE                       139
#define ID_RLGMTHR                      140
#define IDD_RECT_DATA                   140
#define ID_AODQUINTILE                  140
#define IDB_GRID                        140
#define ID_RLGMTMIN                     141
#define IDD_RETURN_DATA                 141
#define ID_AOIQUINT                     141
#define IDD_POPUP                       142
#define IDD_GRAFONT                     143
#define ID_AODTREDEC                    143
#define IDD_GRACOLORS                   144
#define ID_AOITREDEC                    144
#define IDD_GRAPHOPT                    145
#define ID_BIMENU                       145
#define IDD_GRA_FIL_OP                  146
#define ID_RLMENU                       146
#define ID_AODDECILE                    146
#define ID_AOIDECILE                    147
#define ID_BIRECT                       147
#define IDD_EDITDAT                     147
#define IDD_DIRECTORIES                 148
#define IDD_FILE_NAME                   149
#define IDD_FILE_KILL                   150
#define IDD_FILE_EDIT                   151
#define ID_RLTIMEZONE                   151
#define IDD_AST_HELP                    152
#define ID_AODNONPLAN                   153
#define IDD_COMMENT                     153
#define IDD_RELOC_DAT                   154
#define ID_COMMENT_MENU                 154
#define ID_AODHSCUSP                    155
#define IDR_ASTRGRDTYPE                 155
#define ID_AOIHSCUSP                    156
#define IDD_BIRTH_INF                   156
#define IDD_TRANS_INFO                  157
#define IDD_QDT_OPTIONS                 158
#define IDD_PRINT_OPT                   159
#define IDD_ORB_EDIT                    160
#define IDD_CUSTOM                      161
#define IDD_COVER_DAT                   162
#define IDD_ARCHIVE_DAT                 163
#define IDD_PSEUDO                      164
#define IDD_CONVOPT                     165
#define IDD_FIND                        166
#define IDD_REPSTYLES                   167
#define IDD_TRANS_DATA                  168
#define IDD_DIALOG1                     172
#define IDD_SOLARARC                    175
#define IDD_DIALOG2                     177
#define IDD_PARA                        177
#define IDD_HARMONIC                    178
#define IDR_CSS1                        180
#define IDD_FOLDERNAME                  181
#define IDD_SELFOLDER                   182
#define IDD_CHART_SEARCH                185
#define IDD_ADVANCEDOPT                 186
#define IDD_ZIPCODE                     187
#define IDD_SET_LANGUAGE                188
#define IDD_FILEOPEN                    189
#define IDD_CHART_TYPE_PROPPAGE         190
#define IDD_TRANS_INFO_PROP_PAGE        192
#define IDD_TRANS_DATA_PROP_PAGE        193
#define IDD_RETURN_DATA_PROP_PAGE       194
#define IDD_RELOC_DAT_PROP_PAGE         195
#define IDD_PROGRESS_DATA_PROP_PAGE     196
#define IDD_BIRTH_INF_PROP_PAGE         197
#define IDD_SOLARARC_PROP_PAGE          198
#define IDD_HARMONIC_PROP_PAGE          199
#define IDD_COMPAT_BIRTH_INF_PROP_PAGE  200
#define ID_EDIT_DELETE                  206
#define ID_DATA_BIRTHINFO               301
#define ID_DATA_COMPATINFO              302
#define ID_DATA_TRANSITSINFO            303
#define ID_DATA_TRANSITSDATA            304
#define ID_DATA_PROGRESS                305
#define ID_OPMIDGRP                     306
#define ID_DATA_BIRTHRECT               306
#define ID_DATA_COMPATRECT              307
#define ID_DATA_RETURNDATA              308
#define ID_DATA_RELOC                   309
#define ID_CHART_DEFAULT                401
#define ID_CHART_BSO                    402
#define ID_CHART_SIGNHOUSE              403
#define ID_CHART_BSHA                   404
#define ID_CHART_COMPLETE               405
#define ID_CHART_COMPLETEBASMID         406
#define ID_CHART_COMPLETEFULLMID        407
#define ID_CHART_NUMERIC                408
#define ID_CHART_COMPAT                 409
#define ID_CHART_TRANS                  410
#define ID_CHART_PROGRESS               411
#define ID_CHART_COMPOS                 412
#define ID_CHART_RELOC                  414
#define ID_CHART_RETURN                 415
#define ID_OPTIONS_SETUP                601
#define ID_OPTIONS_TEXT                 602
#define ID_OPTIONS_GRAPHICS             603
#define ID_OPTIONS_VIEWER               605
#define ID_OPTIONS_BIRTH                608
#define ID_OPTIONS_COMPATIBILITY        609
#define ID_OPTIONS_TRANSITS             610
#define ID_OPTIONS_PROG                 611
#define ID_OPTIONS_COMPOSITE            612
#define ID_OPTIONS_RELOC                614
#define ID_OPTIONS_NUMERIC              618
#define ID_OPTIONS_ALLCHECK             620
#define ID_OPTIONS_QDT                  621
#define ID_UTILITIESREADFILEDATA        703
#define ID_UTILITES_REINDEXBIRTH        704
#define ID_UTILITIES_REINDEXLOCATION    705
#define ID_UTILITIES_REINDEXALL         706
#define ID_UTILITIES_MAKEPOPUPSBIRTH    707
#define ID_UTILITIES_MAKEPOPUPLOCATION  708
#define ID_UTILITIES_MAKEPOPUPALL       709
#define ID_UTILITIES_MERGEDBBIRTH       710
#define ID_UTILITIES_MERGEDBLOCATION    711
#define ID_UTILITIES_REBUILDFLIST       712
#define ID_UTILITIES_CLEARSELECTION     713
#define ID_UTILITIES_EDITENTRY          714
#define ID_UTILITIES_SORT               715
#define IDC_EDIT1                       1000
#define ID_ARDELETE                     1000
#define IDC_TEXT                        1000
#define IDC_LEFT                        1001
#define ID_FNFILENAME                   1001
#define IDC_CHECK1                      1001
#define IDC_USEEXT                      1001
#define IDC_DBTEXT                      1001
#define IDC_ASTEROID                    1001
#define IDC_TARGET                      1001
#define IDC_GLYPH                       1001
#define IDC_GRIDFILE                    1001
#define IDC_KNOWN                       1001
#define IDC_NOTSURE                     1001
#define IDC_BOTTOM                      1002
#define IDC_CHECK2                      1002
#define IDC_REVCOLOR                    1002
#define IDC_REVBACK                     1002
#define IDC_INTERPRETED                 1002
#define IDC_KEEPSIGNPOLAR               1002
#define IDC_GLYPH2                      1002
#define IDC_AUTO                        1002
#define IDC_RIGHT                       1003
#define IDC_TOP                         1004
#define IDC_PTEXT                       1009
#define IDC_RELOCS                      1016
#define IDC_DBNAME                      1017
#define IDC_NAME                        1018
#define IDC_TXTDBNAME                   1018
#define IDC_EVENT                       1019
#define IDC_CPCOMMENT                   1020
#define IDC_EDIT                        1021
#define IDC_WSPELLCTRL1                 1022
#define IDC_SYSTEM                      1024
#define IDC_MONTH                       1025
#define IDC_DAY                         1026
#define IDC_YEAR                        1027
#define IDC_HARM                        1029
#define IDC_SWAPSIGNPOLAR               1031
#define IDC_GLYPHFONT                   1032
#define IDC_TABCTRLCTRL1                1033
#define IDC_GLYPHFONT2                  1033
#define IDC_WZZIP                       1034
#define IDC_FOLDER                      1036
#define IDC_COMMENTS                    1038
#define IDC_SELECT_FILE                 1039
#define IDC_TRAILER                     1040
#define IDC_ASTROLOGER                  1041
#define IDC_LABELTXT1                   1042
#define IDC_LABELTXT2                   1043
#define IDC_LABELTXT3                   1044
#define IDC_LABELTXT4                   1045
#define IDC_HEADER                      1046
#define IDC_ZIPCODE                     1047
#define IDC_LANGUAGE                    1048
#define IDC_LIST1                       1049
#define IDC_REPORTS                     1051
#define IDC_GRAPHS                      1052
#define IDC_GRIDS                       1053
#define IDC_CHART_TYPE                  1054
#define IDC_DEFRECT                     1056
#define IDC_PROGRESS1                   1057
#define ID_GETBIRTH                     1101
#define ID_ADDBIRTH                     1102
#define ID_REPLACEBIRTH                 1103
#define ID_DELETEBIRTH                  1104
#define ID_MAKEPOPUP                    1105
#define ID_COPYBIRTH                    1106
#define ID_PASTEBIRTH                   1107
#define ID_CLEARBIRTH                   1108
#define ID_RETURN                       1109
#define ID_GETLOCAT                     1201
#define ID_ADDLOCAT                     1202
#define ID_REPLACELOCAT                 1203
#define ID_DELETELOCAT                  1204
#define ID_COPYLOCAT                    1205
#define ID_PASTELOCAT                   1206
#define ID_CLEARLOCAT                   1207
#define ID_VIEW_ZOOMIN                  32771
#define ID_VIEW_ZOOMOUT                 32772
#define ID_HELP_ASTROLOGY               32773
#define ID_VIEW_FITWIN                  32774
#define ID_FILE_OPENBIRTH               32775
#define ID_GRAPH_SHOWSIGNNAME           32776
#define ID_FILE_SAVEBIRTH               32777
#define ID_BOLD                         32777
#define ID_GRAPH_SHOWHOUSENUMBERS       32778
#define ID_ITALIC                       32778
#define ID_GRAPH_SHOWHOUSEDEGREES       32779
#define ID_HEADING                      32779
#define ID_EDIT_SEARCHCONTINUE          32780
#define ID_NORMAL                       32780
#define ID_GRAPH_SHOWASPECTS            32781
#define ID_GRAPH_SHOWASPECTGRID         32782
#define ID_GRAPH_SHOWSIGNLINES          32783
#define ID_GRAPHICS_INNEROUTERHOUSECUSPS 32784
#define ID_GRAPHICS_SIGNTICKWHEEL       32785
#define ID_GRAPHICS_DECANTICKWHEEL      32786
#define ID_GRAPHICS_DEGREETICKWHEEL     32787
#define ID_GRAPHICS_HOUSENUMBERSOUTSIDE 32788
#define ID_GRAPHICS_PLOTCLASSICALLY     32789
#define ID_GRAPHICS_SHOWPLANETDEGREES   32790
#define ID_GRAPHICS_USENEXTCHART        32791
#define ID_GRAPHICS_USEPREVCHART        32792
#define ID_GRAPHICS_USEFIRSTCHART       32793
#define ID_GRAPHICS_INCREASEHOUSECUSPS  32794
#define ID_GRAPHICS_DECREASEHOUSECUSPS  32795
#define ID_GRAPHICS_NORMALHOUSECUSPS    32796
#define ID_FILE_EXPORT                  32797
#define ID_VIEW_LARGERFONT              32798
#define ID_VIEW_SMALLERFONT             32799
#define ID_FILE_OPEN_BIRTH              32800
#define ID_GRAPH_USEGLYPHS              32801
#define ID_OPTIONS_GRAPHICOPTIONS       32802
#define ID_OPTIONS_GRAPHICFILECONVERSIONOPTIONS 32803
#define ID_OPTIONS_DIRECTORIES          32804
#define ID_VIEW_LARGERFONTS             32806
#define ID_OPTIONS_PRINTING             32807
#define ID_OPTIONS_GRAPHICSOPTIONS      32808
#define ID_EDIT_SEARCH                  32809
#define ID_UTILITIES_ARCHIVECHARTS      32810
#define ID_UTILITIES_UNARCHIVECHARTS    32811
#define ID_OPTIONS_GRAPHICFILEOPTIONS   32812
#define ID_OPTIONS_EDITORSETUP          32813
#define ID_OPTIONS_EDITORBS             32814
#define ID_OPTIONS_CHARTOPTIONS_COMPOSITETRANSITS 32815
#define ID_OPTIONS_CHARTOPTIONS_FIXEDSTAR 32816
#define ID_OPTIONS_CHARTOPTIONS_ARABICPOINTSOPTIONS 32817
#define ID_OPTIONS_CHARTOPTIONS_PROBLEMCHARTS 32818
#define ID_CHART_OTHERCHARTS_COMPOSITETRANSITS 32819
#define ID_CHART_SPECIALTYCHARTS_FIXEDSTAR 32820
#define ID_CHART_SPECIALTYCHARTS_ARABICPOINTS 32821
#define ID_CHART_SPECIALTYCHARTS_HELIOCENTRIC 32822
#define ID_CHART_SPECIALTYCHARTS_PROBLEM 32823
#define ID_EDIT_FINDCHART               32824
#define ID_EDIT_FINDNEXT                32825
#define ID_FILE_NEW_COVERPAGE           32826
#define ID_FILE_NEW_COMMENTFILE         32827
#define ID_FILE_OPEN_COVERPAGE          32828
#define ID_FILE_OPEN_COMMENTFILE        32829
#define ID_FILE_NEW_USERFILELIST        32830
#define ID_FILE_OPEN_USERFILELIST       32831
#define ID_FILE_EDIT                    32832
#define ID_HELP_TECHSUPP                32833
#define ID_HELP_CJNOYESSW               32834
#define ID_HELP_VERSIONS                32835
#define ID_HELP_ORDER                   32836
#define ID_SAVERELOC                    32838
#define ID_DELETE_RELOC                 32839
#define ID_GETTRANSIT                   32840
#define ID_ADDTRANSIT                   32841
#define ID_DELETE_TRANSIT               32842
#define ID_GETRELOC                     32844
#define ID_SPELL                        32845
#define ID_SOLARARCCHART                32846
#define ID_SOLARARCDATA                 32847
#define ID_CHART_OTHERCHARTS_SOLARARCDIRECTIONS 32848
#define ID_SOLARARCOPT                  32850
#define ID_DATA_HARMONICDATA            32851
#define ID_Menu                         32852
#define ID_OTHERCHARTS_HARMONIC         32853
#define ID_HARMONIC_OPTIONS             32854
#define ID_OTHERCHARTS_HARMONIC32866    32866
#define ID_FOLDERS_CREATEFOLDER         32869
#define ID_FOLDERS_CHANGE               32870
#define ID_FOLDERS_RENAME               32871
#define ID_Menu32872                    32872
#define ID_Menu32873                    32873
#define ID_OPTIONS_ADVANCED             32874
#define ID_LOOKUP_LONGLAT               32876
#define ID_PASTEACS                     32877
#define ID_Menu32879                    32879
#define ID_SELECTALL                    32880
#define ID_TODAY                        32883
#define ID_COMPRESSDATABASE             32884
#define ID_EPHEMERIS                    32885
#define ID_REFMAPS                      32886
#define ID_BACKUP                       32887
#define ID_MINORCENSUS                  32900
#define ID_OPTIONS_SETCURRENTLANGUAGE   32902
#define ID_CHARTWIZARD                  32904
#define ID_FILE_OPEN_NEW                32905
#define ID_RETURN_W_RELOC               32906
#define ID_RETURN_W_TRANSITS            32907

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32908
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
