// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tabctrlctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CTabctrlctrl1

IMPLEMENT_DYNCREATE(CTabctrlctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTabctrlctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CTabctrlctrl1 operations
