#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTabctrlctrl1 wrapper class

class CTabctrlctrl1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTabctrlctrl1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5230206E, 0x3E6A, 0x454C, { 0x99, 0x99, 0xEA, 0xDA, 0x11, 0xAE, 0x4F, 0x32 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:


// Operations
public:

// _DTabCtrl

// Functions
//


// Properties
//

CString GetTabString()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}
void SetTabString(CString propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}
CString Get_TabString()
{
	CString result;
	GetProperty(0x0, VT_BSTR, (void*)&result);
	return result;
}
void Set_TabString(CString propVal)
{
	SetProperty(0x0, VT_BSTR, propVal);
}

void DoTheClick(short xpos)
{
    short result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I2, (void*)&xpos, NULL);
}

};
