unit wp;
objWP.AppMove ;
objWP.KeyType ('this is a sample of text ') ;
objWP.AttributeAppearanceToggle ( 12 ) ;
objWP.KeyType ('Bold Text') ;
objWP.AttributeAppearanceToggle ( 12 ) ;
objWP.KeyType (' end of bold ') ;
objWP.AttributeAppearanceToggle ( 8 ) ;
objWP.KeyType ('Italic Text') ;
objWP.AttributeAppearanceToggle ( 8 ) ;
objWP.KeyType (' end Italic') ;
objWP.AttributeAppearanceToggle ( 14 ) ;
objWP.KeyType ('Underline') ;
objWP.AttributeAppearanceToggle ( 14 ) ;
oobjWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.PosCharPrevious ;
objWP.KeyType (' ') ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.PosCharNext ;
objWP.KeyType ('line') ;
objWP.HardReturn ;
objWP.HardReturn ;
objWP.FontSize( 233  ) ;
objWP.Justification ( 2 ) ;
objWP.Font ('Arial Regular', 16662,  0 , 90,  0 ,  20 ,  139 ,  0 ) ;
objWP.AttributeAppearanceToggle ( 12 ) ;
objWP.KeyType ('This is a Headline') ;
objWP.HardReturn ;
objWP.Justification ( 0 ) ;

objWP.Font ('Univers-Light-Light Regular', 16662,  0 , 90,  0 ,  20 ,  139 ,   0 ) ;
objWP.QuickFont ('Times New Roman', 200  , 0, 0, 0) ;
objWP.KeyType ('Times new Roman') ;

Var objWP : Variant;
objWP := CreateOleObject( 'WordPerfect.PerfectScript');
objWP.QuickFont ('Arial', 233  , 0, 0, 0,  12 ) ;
objWP.HardReturn ;
objWP.TabSet ( 1 , 2400  ,  0 ) ;

objWP.TabSet(, , );
objWP.TabSet(, , );
objWP.FontSize;
