//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DlgTest.rc
//
#define ID_CANCEL                       2
#define ID_FNSELFILE                    3
#define IDD_ABOUTBOX                    100
#define ID_CSCOGROUP                    100
#define ID_CS_RELOC                     101
#define ID_AHLIST                       101
#define ID_OPCTGRP                      101
#define ID_RDCHECK                      101
#define ID_QDONCE                       101
#define ID_POCOVER                      101
#define ID_ARNAME                       102
#define ID_FNNAME                       102
#define ID_CSPROGR                      102
#define ID_AHVIEW                       102
#define ID_OPTROPICAL                   102
#define ID_PDSYSTEM                     102
#define ID_RDBODY                       102
#define ID_CPIMAGE                      102
#define ID_POCMT                        102
#define ID_AOCONTEXT                    102
#define ID_FENAME                       102
#define ID_FKNAME                       102
#define ID_QDRESTRICTTIM                102
#define ID_BINAME                       102
#define ID_CSPRGCUSP                    103
#define ID_AHPRINT                      103
#define ID_OPSIDEREAL                   103
#define ID_RDMETHOD                     103
#define ID_ARCMD                        104
#define ID_FNCOMMENT                    104
#define ID_AHCONVERT                    104
#define ID_PDYEAR                       104
#define ID_CPGRAPHIC                    104
#define ID_FECOMMENTS                   104
#define ID_FKCOMMENT                    104
#define ID_BISEX                        104
#define ID_CSOOGROUP                    105
#define ID_TDSTART                      105
#define ID_OPHOUSEPROC                  105
#define ID_RDSMO                        105
#define ID_QDFHR                        105
#define ID_ARGRP                        106
#define ID_FNTYPE                       106
#define ID_CSTEXT                       106
#define ID_OPHOUSES                     106
#define ID_PDMO                         106
#define ID_RDHRS                        106
#define ID_CPTITLE                      106
#define ID_FETYPE                       106
#define ID_FKTYPE                       106
#define ID_DMAIN                        106
#define ID_BIMO                         106
#define ID_ARLHA                        107
#define ID_CSGRAPH                      107
#define ID_TDEND                        107
#define ID_OPASPECTS                    107
#define ID_RDSDAY                       107
#define ID_QDFMIN                       107
#define ID_DHELP                        107
#define ID_ARZIP                        108
#define ID_CSDATAFILE                   108
#define ID_OPEXTASP                     108
#define ID_PDDAY                        108
#define ID_RDMIN                        108
#define ID_CP_SUBJECT                   108
#define ID_FEFILENAME                   108
#define ID_FKFILENAME                   108
#define ID_DDATABASE                    108
#define ID_BIDAY                        108
#define ID_OPMISC                       109
#define ID_RDSYEAR                      109
#define ID_FKCONTINUE                   109
#define ID_QDFAMPM                      109
#define ID_DDATA                        109
#define ID_CSDFTYPE                     110
#define ID_TDMO                         110
#define ID_OPEXTMISC                    110
#define ID_PDTARGET                     110
#define ID_RDAMPM                       110
#define ID_CPCOMMENT                    110
#define ID_AODCONJUNCT                  110
#define ID_DUSER                        110
#define ID_BIYEAR                       110
#define ID_CSCUSTOM                     111
#define ID_OPSUMMARY                    111
#define ID_AOICONJUNCT                  111
#define ID_TDDAY                        112
#define ID_OPVERTEAST                   112
#define ID_RDKNOWNANGL                  112
#define ID_RDEMO                        112
#define ID_QDLHR                        112
#define ID_CPFONT                       112
#define ID_BIHR                         112
#define ID_OPTEXT                       113
#define ID_AODSEXTILE                   113
#define ID_TDNUM                        114
#define IDOPMBASE                       114
#define ID_RDKSIGN                      114
#define ID_RDEDAY                       114
#define ID_QDLMIN                       114
#define ID_CPASTROLOGER                 114
#define ID_AOISEXT                      114
#define ID_BIMIN                        114
#define ID_OPMFULL                      115
#define ID_OPMHALF                      116
#define ID_RDKDEG                       116
#define ID_RDEYEAR                      116
#define ID_QDLAMPM                      116
#define ID_AODTRINE                     116
#define ID_BIAMPM                       116
#define ID_OPMMIDASP                    117
#define ID_AOITRINE                     117
#define ID_RDKMIN                       118
#define ID_POHDP1                       118
#define ID_RDPROG                       118
#define ID_CMTB4T                       119
#define ID_AODOPPOSE                    119
#define ID_RLCOUNTRY                    119
#define ID_RDPROGSYS                    120
#define ID_POCTRHD                      120
#define ID_AOIOPPOSE                    120
#define ID_POSTYLES                     121
#define ID_RLSTATE                      121
#define ID_AODSQUARE                    122
#define ID_RDPYEAR                      123
#define ID_AOISQUARE                    123
#define ID_RLLOCATION                   123
#define ID_RDPMO                        125
#define ID_AODSSEXT                     125
#define ID_RLLODEG                      125
#define ID_AOISSEXT                     126
#define ID_RDPDAY                       127
#define ID_RLLOMIN                      127
#define IDR_MAINFRAME                   128
#define ID_AODSSQARE                    128
#define ID_RLEASTWEST                   128
#define IDR_DLGTESTYPE                  129
#define ID_RDTARGET                     129
#define ID_AOISSQUARE                   129
#define IDD_ARCHIVE_DAT                 130
#define ID_AODSSESQUIQ                  131
#define IDD_FILE_NAME                   131
#define ID_RLLADEG                      131
#define ID_AOISSESQUIQ                  132
#define IDD_FILE_EDIT                   132
#define IDD_FILE_KILL                   133
#define ID_RLLAMIN                      133
#define ID_AODQUIN                      134
#define IDD_CUSTOM                      134
#define ID_RLNORTHSOUTH                 134
#define ID_AOIQUINCUNX                  135
#define IDD_TRANS_DATA                  135
#define IDD_AST_HELP                    136
#define ID_AODBIQUI                     137
#define IDD_OPTIONS                     137
#define ID_AOIBQUINT                    138
#define IDD_PROGRESS_DATA               139
#define ID_RLSPECCODE                   139
#define ID_AODQUINTILE                  140
#define IDD_RECT_DATA                   140
#define ID_RLGMTHR                      140
#define ID_AOIQUINT                     141
#define IDD_RETURN_DATA                 141
#define ID_RLGMTMIN                     141
#define ID_AODTREDEC                    143
#define IDD_QDT_OPTIONS                 143
#define ID_AOITREDEC                    144
#define IDD_COVER_DAT                   144
#define IDD_PRINT_OPT                   145
#define ID_BIMENU                       145
#define ID_AODDECILE                    146
#define ID_RLMENU                       146
#define ID_AOIDECILE                    147
#define ID_BIRECT                       147
#define IDD_DIRECTORIES                 148
#define ID_RLTIMEZONE                   151
#define IDD_ORB_EDIT                    152
#define ID_AODNONPLAN                   153
#define IDD_RELOC_DAT                   154
#define ID_AODHSCUSP                    155
#define ID_AOIHSCUSP                    156
#define IDD_BIRTH_INF                   156
#define IDD_TRANS_INFO                  157
#define ID_OPMIDGRP                     306
#define ID_ARDELETE                     1000
#define ID_FNFILENAME                   1001
#define ID_GETBIRTH                     1101
#define ID_ADDBIRTH                     1102
#define ID_REPLACEBIRTH                 1103
#define ID_DELETEBIRTH                  1104
#define ID_MAKEPOPUP                    1105
#define ID_COPYBIRTH                    1106
#define ID_PASTEBIRTH                   1107
#define ID_CLEARBIRTH                   1108
#define ID_RETURN                       1109
#define ID_GETLOCAT                     1201
#define ID_ADDLOCAT                     1202
#define ID_REPLACELOCAT                 1203
#define ID_DELETELOCAT                  1204
#define ID_COPYLOCAT                    1205
#define ID_PASTELOCAT                   1206
#define ID_CLEARLOCAT                   1207
#define ID_DIALOGS_ARCHIVEFILES         32771
#define ID_DIALOGS_COVERPAGEDATA        32772
#define ID_DIALOGS_CUSTOMIZE            32773
#define ID_DIALOGS_FILEDATAEDIT         32774
#define ID_DIALOGS_KILLAFILE            32775
#define ID_DIALOGS_FILENAME             32776
#define ID_DIALOGS_OPTIONS              32777
#define ID_DIALOGS_ORBEDIT              32778
#define ID_DIALOGS_PRINTOPTIONS         32779
#define ID_DIALOGS_PROGRESSDATA         32780
#define ID_DIALOGS_QDTOPTIONS           32781
#define ID_DIALOGS_RECTIFICATION        32782
#define ID_DIALOGS_RETURNDATA           32783
#define ID_DIALOGS_TRANSITDATA          32784
#define ID_DIALOGS_DIRECTORIES          32785
#define ID_DATARELOCATION               32786
#define ID_DATA_TRANSITINFO             32787
#define ID_DATA_BIRTHINFO               32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
